# Generated by Django 5.2 on 2025-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(choices=[(1, 'Table 1'), (2, 'Table 2'), (3, 'Table 3'), (4, 'Table 4'), (5, 'Table 5'), (6, 'Table 6'), (7, 'Table 7'), (8, 'Table 8'), (9, 'Table 9'), (10, 'Table 10'), (11, 'Table 11'), (12, 'Table 12'), (13, 'Table 13'), (14, 'Table 14'), (15, 'Table 15'), (16, 'Table 16'), (17, 'Table 17'), (18, 'Table 18'), (19, 'Table 19'), (20, 'Table 20')])),
                ('customer_name', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_request', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
