# Generated by Django 5.2 on 2025-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_menuitem_remove_orderitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
