# Generated by Django 5.2 on 2025-05-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
