# Generated by Django 5.2 on 2025-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_remove_reservation_email_remove_reservation_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
